dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"

install:
- pip install -r requirements.txt
- pip install nose flexmock

script: nosetests
