---
name: Lint Python issues

on:
  push:
  pull_request:
    branches: [main]

jobs:
  python-lint-job:
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - id: VCS_Diff_Lint
        name: VCS Diff Lint
        uses: fedora-copr/vcs-diff-lint-action@v1

      - name: Upload artifact with detected defects in SARIF format
        uses: actions/upload-artifact@v3
        with:
          name: VCS Diff Lint SARIF
          path: ${{ steps.VCS_Diff_Lint.outputs.sarif }}
        if: ${{ always() }}

      - name: Upload SARIF to GitHub using github/codeql-action/upload-sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.VCS_Diff_Lint.outputs.sarif }}
        if: ${{ always() }}
